// Generated by CoffeeScript 1.10.0
module.exports = function(grunt) {
  return grunt.initConfig({
    pkg: grunt.file.readJSON("package.json"),
	// TODO jshint
    jasmine_node: {
      options: {
        forceExit: true,
        match: ".",
        matchall: false,
        specNameMatcher: "spec"
      },
      all: ["test/spec/"]
    },
    coffee: {
      main: {
        options: {
          sourceMap: true
        },
        files: {
          "build/audiochart.js": "audiochart.coffee"
        }
      },
      specs: {
        expand: true,
        cwd: 'spec/',
        src: ['*.spec.coffee'],
        dest: 'test/spec/',
        ext: '.spec.js'
      }
    },
    uglify: {
      options: {
        banner: '/*! <%= pkg.name %> ' + '<%= grunt.template.today("yyyy-mm-dd") %> */\n',
        sourceMap: true,
        sourceMapIn: "build/audiochart.js.map"
      },
      build: {
        src: "build/audiochart.js",
        dest: "build/audiochart.min.js"
      }
    },
    copy: {
      main: {
        src: "spec/HTMLTableDataWrapper.fixtures.html",
        dest: "test/spec/HTMLTableDataWrapper.fixtures.html"
      }
    },
    curl: {
      "test/jasmine-all-min.js": "http://searls.github.io/jasmine-all/jasmine-all-min.js",
      "test/jasmine-dom-fixtures.js": "https://github.com/jeffwatkins/jasmine-dom/raw/master/lib/" + "jasmine-dom-fixtures.js"
    }
  },

  grunt.loadNpmTasks("grunt-jasmine-node-new"),
  grunt.loadNpmTasks("grunt-contrib-uglify"),
  grunt.loadNpmTasks("grunt-contrib-copy"),
  grunt.loadNpmTasks("grunt-curl"),
  grunt.loadNpmTasks("grunt-if-missing"),

  grunt.registerTask("default", [
	"jasmine_node",
	"uglify",
	"copy",
	"if-missing:curl"
  ]));
};
