// Generated by CoffeeScript 1.10.0
var ac;

if (typeof exports !== "undefined" && exports !== null) {
  ac = require('../audiochart');
} else {
  ac = window;
}

describe('_AudioChart', function() {
  return it('TBD', function() {
    return expect(true).toBe(true);
  });
});
