// Generated by CoffeeScript 1.7.1
(function() {
  var HTML_FILE_NAME, ac, dw, headless, jsdom, run_tests;

  if (typeof exports !== "undefined" && exports !== null) {
    ac = require('../audiochart');
    dw = require('./DataWrappers.common.spec');
    jsdom = require('jsdom');
    headless = true;
  } else {
    ac = window;
    dw = window;
    headless = false;
  }

  HTML_FILE_NAME = 'HTMLTableDataWrapper.fixtures.html';

  run_tests = function(doc) {
    return dw.data_wrappers_test_core('HTMLDataWrapper', new ac.HTMLTableDataWrapper(doc, 'test_one'), new ac.HTMLTableDataWrapper(doc, 'test_neg'));
  };

  if (headless) {
    jsdom.env({
      file: __dirname + '/' + HTML_FILE_NAME,
      done: function(errors, window) {
        return run_tests(window.document);
      }
    });
  } else {
    loadFixtures('/spec/' + HTML_FILE_NAME);
    run_tests(window.document);
  }

}).call(this);
